import { Config } from "effect"

export function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

const copy = process.env["OPENAGENT_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]

function enabledByExperimental(key: string) {
  return process.env[key] === undefined ? truthy("OPENAGENT_EXPERIMENTAL") : truthy(key)
}

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  OPENAGENT_AUTO_HEAP_SNAPSHOT: truthy("OPENAGENT_AUTO_HEAP_SNAPSHOT"),
  OPENAGENT_GIT_BASH_PATH: process.env["OPENAGENT_GIT_BASH_PATH"],
  OPENAGENT_CONFIG: process.env["OPENAGENT_CONFIG"],
  OPENAGENT_CONFIG_CONTENT: process.env["OPENAGENT_CONFIG_CONTENT"],
  OPENAGENT_DISABLE_AUTOUPDATE: truthy("OPENAGENT_DISABLE_AUTOUPDATE"),
  OPENAGENT_ALWAYS_NOTIFY_UPDATE: truthy("OPENAGENT_ALWAYS_NOTIFY_UPDATE"),
  OPENAGENT_DISABLE_PRUNE: truthy("OPENAGENT_DISABLE_PRUNE"),
  OPENAGENT_DISABLE_TERMINAL_TITLE: truthy("OPENAGENT_DISABLE_TERMINAL_TITLE"),
  OPENAGENT_SHOW_TTFD: truthy("OPENAGENT_SHOW_TTFD"),
  OPENAGENT_DISABLE_AUTOCOMPACT: truthy("OPENAGENT_DISABLE_AUTOCOMPACT"),
  OPENAGENT_DISABLE_MODELS_FETCH: truthy("OPENAGENT_DISABLE_MODELS_FETCH"),
  OPENAGENT_DISABLE_MOUSE: truthy("OPENAGENT_DISABLE_MOUSE"),
  OPENAGENT_FAKE_VCS: process.env["OPENAGENT_FAKE_VCS"],
  OPENAGENT_SERVER_PASSWORD: process.env["OPENAGENT_SERVER_PASSWORD"],
  OPENAGENT_SERVER_USERNAME: process.env["OPENAGENT_SERVER_USERNAME"],

  // Experimental
  OPENAGENT_EXPERIMENTAL_FILEWATCHER: Config.boolean("OPENAGENT_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  OPENAGENT_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("OPENAGENT_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  OPENAGENT_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("OPENAGENT_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  OPENAGENT_MODELS_URL: process.env["OPENAGENT_MODELS_URL"],
  OPENAGENT_MODELS_PATH: process.env["OPENAGENT_MODELS_PATH"],
  OPENAGENT_DB: process.env["OPENAGENT_DB"],

  OPENAGENT_WORKSPACE_ID: process.env["OPENAGENT_WORKSPACE_ID"],
  OPENAGENT_EXPERIMENTAL_WORKSPACES: enabledByExperimental("OPENAGENT_EXPERIMENTAL_WORKSPACES"),
  OPENAGENT_EXPERIMENTAL_SESSION_SWITCHER: enabledByExperimental("OPENAGENT_EXPERIMENTAL_SESSION_SWITCHER"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get OPENAGENT_DISABLE_PROJECT_CONFIG() {
    return truthy("OPENAGENT_DISABLE_PROJECT_CONFIG")
  },
  get OPENAGENT_EXPERIMENTAL_REFERENCES() {
    return enabledByExperimental("OPENAGENT_EXPERIMENTAL_REFERENCES")
  },
  get OPENAGENT_TUI_CONFIG() {
    return process.env["OPENAGENT_TUI_CONFIG"]
  },
  get OPENAGENT_CONFIG_DIR() {
    return process.env["OPENAGENT_CONFIG_DIR"]
  },
  get OPENAGENT_PURE() {
    return truthy("OPENAGENT_PURE")
  },
  get OPENAGENT_PERMISSION() {
    return process.env["OPENAGENT_PERMISSION"]
  },
  get OPENAGENT_PLUGIN_META_FILE() {
    return process.env["OPENAGENT_PLUGIN_META_FILE"]
  },
  get OPENAGENT_CLIENT() {
    return process.env["OPENAGENT_CLIENT"] ?? "cli"
  },
}
